---
title: "Exploracion monitoreo aves"
author: "Gorgia Graells"
date: "2/3/2020"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

###Metodología

Orden de datos en donde todas las presencia de la base de datos quedan como abundancias de cada especie para cada sitio muestreado.

Se calculó la riqueza mínima y máxima de especies y la riqueza acumulada de especies (100 permutaciones) por temporada estudiada.

Se calculó el índice de diversidad de Shannon para especies de aves por cada sitio por temporada de muestreo. Se comparó la diferencia entre la diversidad de invierno y primavera revisando su aumento o disminución para cada sitio estudiado. Se comparó la diversidad por ambientes para cada temporada estudiada.

NMDS:
Análisis de cluster a partir de matriz de dissimilaridades. Separación de grupos a partir de dendrograma

seleccion variables ambientales mediante stepwise (funcion ordistep) para las dos temporadas de estudio

#Resultados


