---
title: "Tablas_Ms_ HabitatAves"
author: "Giorgia Graells"
date: "10/16/2020"
output: 
  pdf_document: 
    keep_tex: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(kableExtra)
library(tidyverse)

```

```{r covariables, results='asis'}
DF_cov <- tibble( `Detection covariables`= c("Temperatura","Humedad", "DirViento" ,"RapViento", "Agua", " ", " ", " ", " ", " ", " ", " "), 
                   `Occupancy covariables`= c("Vegetation cover","Altitude","Distance to river",
                                              "Grassland", "Shrublands", "Native forest","Tree plantation" ,"Crops" ,
                                              "Paved surface","Sand", "Gravel", "Ocean" )
                   )

kable(DF_cov, booktabs=T, escape = F) %>% kable_styling(latex_options = "basic") %>% column_spec(column = 1, italic = T)

 


```

```{r ModPredRiqueza}
# GLMmixto con variables aleatorias
library(MuMIn)

AvesInv_riq <- readRDS("AvesInv_riq.rds")
nuevoinv <- AvesInv_riq  %>% mutate(Temporada="Winter") %>% 
  mutate(Ambiente = case_when(AMBIENTE == "PLAYA INTERVENIDA"| AMBIENTE =="PLAYA NATURAL"~"Beach",
                              AMBIENTE =="ROQUERIO INTERVENIDO"| AMBIENTE =="ROQUERIO NATURAL"~"Rocky shore",
                              AMBIENTE =="URBANO" | AMBIENTE == "VERDE"~"Land")) %>% 
  mutate(Grado_modificacion=case_when(AMBIENTE == "PLAYA INTERVENIDA"| AMBIENTE =="ROQUERIO INTERVENIDO" |AMBIENTE =="URBANO"~"Modified",
                                      AMBIENTE == "PLAYA NATURAL"| AMBIENTE =="ROQUERIO NATURAL" |AMBIENTE =="VERDE"~"Natural" ))

AvesPrim_riq <- readRDS("AvesPrim_riq.rds")
nuevoprim <- AvesPrim_riq %>% ungroup() %>% mutate(Temporada="Spring") %>% 
  mutate(Ambiente = case_when(AMBIENTE == "PLAYA INTERVENIDA"| AMBIENTE =="PLAYA NATURAL"~"Beach",
                              AMBIENTE =="ROQUERIO INTERVENIDO"| AMBIENTE =="ROQUERIO NATURAL"~"Rocky shore",
                              AMBIENTE =="URBANO" | AMBIENTE == "VERDE"~"Land")) %>% 
  mutate(Grado_modificacion=case_when(AMBIENTE == "PLAYA INTERVENIDA"| AMBIENTE =="ROQUERIO INTERVENIDO" |AMBIENTE =="URBANO"~"Modified",
                                      AMBIENTE == "PLAYA NATURAL"| AMBIENTE =="ROQUERIO NATURAL" |AMBIENTE =="VERDE"~"Natural" ))

Riqueza <- bind_rows(nuevoinv, nuevoprim)

# Modelo
Modelo <- glm(Riqueza ~ Temporada + Ambiente + Grado_modificacion + Habitat +  Temporada:Ambiente + Ambiente:Grado_modificacion , family = poisson, data =Riqueza ) 
options(na.action = "na.fail")
#Seleccion de modelos

Selected <- dredge(Modelo, m.lim = c(0, floor(nrow(Riqueza)/10)))

Final <- subset(Selected, delta < 2)
Final_conpeso <- model.sel(Final)

Final_DF <- as.data.frame(Final_conpeso)
kable(Final_DF, digits = 2, booktabs=T) %>%  kable_styling(latex_options = c("scale_down"), font_size = 9)

```


```{r ModGLMEstacion,results='asis'}
#Modelo 1= Abundancia ~ Estacion * Especie + AMBIENTE+ (1|Sitio), family = poisson, data =Aves ) #AIC 17716.1
#Modelo 2= Abundancia ~ Especie + AMBIENTE+ (1|Sitio), family = poisson, data =Aves )           #AIC 18241.0
DF_seasson <- tibble(Model= c("$Estacion \\times Especie + Ambiente+ \\frac{1}{Sitio}$", "$Especie + Ambiente + \\frac{1}{Sitio}$"), AIC= c(17716.1, 18241.0))

kable(DF_seasson, booktabs=T, escape = F) %>% kable_styling(latex_options = "basic") 

```


```{r SimperInv, results='asis'}
Inv_DF <-  read.csv("ResumenSimper_Inv2.csv") %>% as.data.frame() 
kable(Inv_DF, booktabs = T) 

```


```{r SimperPrim, results='asis'}
Prim_DF <-  read.csv("ResumenSimper_Prim2.csv") %>% as.data.frame()
kable(Prim_DF, booktabs = T) 

```


```{r ModOcuPrim, results='asis'}
DF_occu <- tibble( Species= c("Columba livia", "Larus dominicanus", "Leucophaeus pipixcan", "Pelecanus thagus", "Phalacrocorax bougainvillii"), 
                   Equation= c("$\\psi_{Cl} = e^{-39.76 + 45.23Na - 21.04Gr + 44.82Sa}$",
                               "$\\psi_{Ld} = e^{12.45}$", 
                               "$\\psi_{Lp} = e^{47.82 -5.09Al -231.04Gr + 5.74Oc + 	4.40Pa}$", 
                               "$\\psi_{Pt} = e^{104.91 -0.59Al +	6.56Na	-2.93Sh -18.98Sa}$", 
                               "$\\psi_{Pb} = e^{-82.05 + 12.46Cr -15.13Gr + 	1.38Oc}$"))

kable(DF_occu, booktabs=T, escape = F) %>% kable_styling(latex_options = "basic") %>% column_spec(column = 1, italic = T)

```


```{r ModOcuInv, results='asis'}
DF_occu <- tibble( Species= c("Columba livia","Coragyps atratus", "Larosterna inca", "Larus dominicanus", "Leucophaeus modestus", "Pelecanus thagus", "Sephanoides sephaniodes", "Turdus falcklandii"), 
                   Equation= c("$\\psi_{Cl} = e^{-1.77 + 1.83Sa}$", 
                               "$\\psi_{Ca} = e^{7.57 -3.29Pa +	33.80Sa}$", 
                               "$\\psi_{Li} = e^{140.42 -2.38Al	-92.31Na -38.88Sa}$", 
                               "$\\psi_{Ld} = e^{2289.33}$",
                               "$\\psi_{Lm} = e^{190.57 + 2.73Ve -4.07Al -134.07Gr +	20.05Sa}$", 
                               "$\\psi_{Pt} = e^{172.98 -2.01Al	-50.93Na -165.09Gr +	2.47Oc}$", 
                               "$\\psi_{Ss} = e^{-106.91 + 1.64Ve +	7.14Al -43.91Na +	5.09Sh -24.45Tr}$", 
                               "$\\psi_{Tf} = e^{687.42 + 29.20Ve +	48.41Al -34.88Oc	-505.66Gs +	59.49Tr -4.94Pa +	283.63Sa -51.82Tr}$"))

kable(DF_occu, booktabs=T, escape = F) %>% kable_styling(latex_options = "basic") %>% column_spec(column = 1, italic = T)

```


